remote_theme: jekyll/minima
url: "https://hezibbeerpro.github.io"
baseurl: "/Ranni-Website"

title: "רני באר - אתר אישי של רני"
description: "ברוכים הבאים לאתר הרשמי של רני באר! כאן תוכלו למצוא את כל הדברים שרני אוהב."
author: "רני באר"
lang: "he"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed