remote_theme: jekyll/minima
url: "https://hezibbeer.github.io"
baseurl: "/Rani-Website"

title: "רני באר - אתר אישי של רני"
description: "ברוכים הבאים לאתר הרשמי של רני באר! כאן תוכלו למצוא את כל הדברים שרני אוהב."
author: "רני באר"
lang: "he"

# SEO
google_site_verification: ""

plugins:
  - jekyll-sitemap
  - jekyll-feed

